[micronaut.application]
name = "demo"

[micronaut.views.thymeleaf]
enabled = true
prefix = "/views/"
suffix = ".html"

[datasources.default]
url = "jdbc:mysql://localhost:3306/mydatabase"
driverClassName = "com.mysql.cj.jdbc.Driver"
username = "root"
password = "123456"
db-type = "mysql"
dialect = "MYSQL"

[liquibase.datasources.default]
change-log = "classpath:db/liquibase-changelog.xml"

[netty.default.allocator]
max-order = 3